### PR TITLE
Chunk data based on the buffer capacity

### LINKED ISSUE #5: `ConnectionOutputStream.write` throws exception if called with sufficiently large payload
Results in the following:
```
java.nio.BufferOverflowException
	at java.base/java.nio.ByteBuffer.put(ByteBuffer.java:1189)
	at com.ngrok.net.ConnectionOutputStream.write(ConnectionOutputStream.java:27)
...
```

Instead of throwing an exception, it should chunk the payload based on the internal buffer size (currently set to 1024 bytes). We should also increase the buffer size to 4k.

### PR DESCRIPTION
**Pull request by nikolay-ngrok**
Fixes: #5
Replaces: #3 

If we attempt to write an array bigger then our capacity, we should automatically split it in chunks and write these, as opposed to throwing array out of bounds exc. 

Also, increase the buffer size to 4k.

### CODE REVIEW

File: ngrok-java/src/main/java/com/ngrok/net/ConnectionSocketImpl.java [hunk 1]
```diff
@@ -22,11 +22,11 @@ protected void setConnection(Connection connection) {
 
     @Override
     protected InputStream getInputStream() throws IOException {
-        return new ConnectionInputStream(connection, 1024);
+        return new ConnectionInputStream(connection, 4096);
```
Comment (CarlAmko) [inline ngrok-java/src/main/java/com/ngrok/net/ConnectionSocketImpl.java:25]: Should we define this as a const?

```
    private static final int STREAM_BUFFER_SIZE = 4096;
```

Comment (nikolay-ngrok) [reply ngrok-java/src/main/java/com/ngrok/net/ConnectionSocketImpl.java:25]: 🤔 maybe? They are not intended/necessarily of the same size

Comment (nikolay-ngrok) [reply ngrok-java/src/main/java/com/ngrok/net/ConnectionSocketImpl.java:25]: actually, I'd rather have it like this, instead of another indirection 🤷

**Review by CarlAmko — APPROVED** [review]
